### ISSUE TITLE
Can you add prop for action after click?

### ISSUE THREAD

**Issue by tranvannhat** [PandiyanCool/angular-clipboard-auto#2]
Can you add prop for action after click?

**Comment by PandiyanCool** [comment]
Do you want a callback function for click event?

**Comment by tranvannhat** [comment]
> Do you want a callback function for click event?

yes, can you help me?

**Comment by PandiyanCool** [comment]
I can try that on the weekend.

**Comment by PandiyanCool** [comment]
@tranvannhat If you can add it. Please add and send a PR.

**Comment by tranvannhat** [comment]
with angular 6, i build prod, lib not working!

**Comment by PandiyanCool** [comment]
@tranvannhat Its built on angular 5
But still it should support angular 6, I guess.
